close, /all
a = obj_new('pulsewaves', inputFile = '/Users/moi/git/pulsewaves/pulsewaves/data/riegl_example1.pls')
;dum = a.readPulses(/ALL)

ALL = ALL,$
HEADERSIZE = HEADERSIZE,$
OFFSETPULSE = OFFSETPULSE,$
NPULSES = NPULSES,$
NVLRECORDS = NVLRECORDS,$
NAVLRECORDS = NAVLRECORDS,$
TSCALE = TSCALE,$
TOFFSET = TOFFSET,$
TMIN = TMIN,$
TMAX = TMAX,$
XSCALE = XSCALE,$
YSCALE = YSCALE,$
ZSCALE = ZSCALE,$
XOFFSET = XOFFSET,$
YOFFSET = YOFFSET,$
ZOFFSET = ZOFFSET,$
XMIN = XMIN,$
XMAX = XMAX,$
YMIN = YMIN,$
YMAX = YMAX,$
ZMIN = ZMIN,$
ZMAX = ZMAX,$
BOUNDINGBOX = BOUNDINGBOX
